import Head from 'next/head';
import styled from 'styled-components';
import Posts from '../Components/Posts';
import { getPost } from '../services';

export default function Home({blogs}) {
  return (
    <Container>
      <Head>
        <title>Graphql Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        {blogs.map((item, i) => (
          <Posts item={item.node} key={i}/>
        ))}
      </Content>
      </Container>
  )
}

export const getStaticProps = async () =>{
  const blogs = await (getPost()) || [];

  return{
    props : {
      blogs
    }
  }
} 

const Container = styled.div`
  width: 80%;
  margin: 1rem auto;
  `
const Content = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-evenly;
  flex-wrap: wrap;
  gap: 1rem;
`
